name: "Create Percy screenshots"

on:
  workflow_run:
    workflows:
      - "Upload artifacts for Percy screenshots"
    types:
      - completed

jobs:
  upload:
    name: Build project with proposed changes & take Percy snapshots
    runs-on: ubuntu-latest
    outputs:
      pr_head_sha: ${{ steps.get_pr_data.outputs.sha }}
      percy_build_link: ${{ steps.percy_snapshot.outputs.build_link }}
      percy_org_id: ${{ steps.percy_snapshot.outputs.org_id }}
      percy_build_id: ${{ steps.percy_snapshot.outputs.build_id }}
      percy_build_state: ${{ steps.percy_build_results.outputs.build_state }}
      percy_num_snapshots: ${{ steps.percy_build_results.outputs.num_snapshots }}
      percy_review_state: ${{ steps.percy_build_results.outputs.review_state }}
      percy_review_state_reason: ${{ steps.percy_build_results.outputs.review_state_reason }}
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4

      - name: Download artifact from workflow run
        uses: actions/download-artifact@v4
        with:
          name: "web-artifact-${{ github.event.workflow_run.id }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get PR data
        if: github.event.workflow_run.event=='pull_request'
        id: get_pr_data
        run: |
          set -e
          echo "sha=$(cat pr_head_sha.txt)" >> $GITHUB_OUTPUT
          echo "pr=$(cat pr_num.txt)" >> $GITHUB_OUTPUT

      - name: Create initial Percy status check
        if: github.event.workflow_run.event=='pull_request'
        id: create_percy_initial_status_check
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{github.repository}}/check-runs
          owner: octokit
          repo: request-action
          name: "percy_upload"
          head_sha: ${{ steps.get_pr_data.outputs.sha }}
          status: in_progress
          details_url: ${{ steps.percy_snapshot.outputs.build_link }}
          output: |
            title: "Percy build"
            summary: "Percy build #${{ steps.percy_snapshot.outputs.build_id }} created"
            text: "Percy build was created at ${{ steps.percy_snapshot.outputs.build_link }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify that triggering workflow run passed
        run: |
          set -e
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Previous workflow run was not successful."
            exit 1
          else
            echo "Previous workflow run was successful."
          fi

      - name: Replace SCM files with artifact files
        run: |
          set -e
          rm -rf templates/docs/examples/ scss/
          mv examples/ templates/docs/.
          tree

      - name: Install NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Take snapshots & upload to Percy
        id: percy_snapshot
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_WRITE }}
          PERCY_PULL_REQUEST: ${{ steps.get_pr_data.outputs.pr }}
          PERCY_COMMIT: ${{ steps.get_pr_data.outputs.sha }}
        run: |
          set -e
          
          echo "build_link=https://percy.io/bb49709b/test-vanilla-gha-migration/builds/34252514" >> $GITHUB_OUTPUT
          echo "org_id=bb49709b" >> $GITHUB_OUTPUT
          echo "build_id=34252514" >> $GITHUB_OUTPUT
          echo "Percy build created at $build_link"

      - name: Wait for Percy build to complete
        run: npx percy build:wait --build ${{ steps.percy_snapshot.outputs.build_id }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_READ }}

      # See endpoint docn: https://www.browserstack.com/docs/percy/api-reference/builds#get-build-details
      - name: Get Percy build results
        id: percy_build_results
        run: |
          response=$(curl --request GET \
          	--url https://percy.io/api/v1/builds/${{ steps.percy_snapshot.outputs.build_id }} \
            --header "Authorization: Token ${{ secrets.PERCY_TOKEN_READ }}"
          )

          build_state=$(echo $response | jq '.data.attributes."state"')
          review_state=$(echo $response | jq '.data.attributes."review-state"')
          review_state_reason=$(echo $response | jq '.data.attributes."review-state-reason"')
          num_snapshots=$(echo $response | jq '.data.attributes."total-snapshots"')
          
          echo "build state $build_state"
          echo "review_state $review_state"
          echo "review_state_reason $review_state_reason"
          echo "num_snapshots $num_snapshots"
          
          echo "build_state=$build_state" >> $GITHUB_OUTPUT
          echo "review_state=$review_state" >> $GITHUB_OUTPUT
          echo "review_state_reason=$review_state_reason" >> $GITHUB_OUTPUT
          echo "num_snapshots=$num_snapshots" >> $GITHUB_OUTPUT

      - name: Create final Percy status check
        if: github.event.workflow_run.event=='pull_request'
        id: create_percy_final_status_check
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{github.repository}}/check-runs
          owner: octokit
          repo: request-action
          name: "percy_upload"
          head_sha: ${{ steps.get_pr_data.outputs.sha }}
          status: completed
          conclusion: ${{ steps.percy_build_results.outputs.review_state == '\"approved\"' && 'success' || 'failure' }}
          details_url: ${{ steps.percy_snapshot.outputs.build_link }}
          output: |
            title: "Percy build"
            summary: "Percy build #${{ steps.percy_snapshot.outputs.build_id }} completed: ${{ steps.percy_build_results.outputs.review_state }}"
            text: |
              Percy build was finished at ${{ steps.percy_snapshot.outputs.build_link }}
              Build is associated with PR https://github.com/${{github.repository}}/pull/${{ steps.get_pr_data.outputs.pr }}
              There were ${{ steps.percy_build_results.outputs.num_snapshots }} total snapshot(s) taken.
              The review state reason is: ${{ steps.percy_build_results.outputs.review_state_reason }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}